protected/controllers/UsersController.php
<?php

class UsersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	//public $layout='//layouts/layout';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'register'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update', 'welcome'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Users;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Users']))
		{
			$model->attributes=$_POST['Users'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Users']))
		{
			$model->attributes=$_POST['Users'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Users');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Users('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Users']))
			$model->attributes=$_GET['Users'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Users::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	public function actionRegister()
	{
		$user_model=new Users('register');
		$creator_model=new CreatorDetails('register');
		$invite_id = CHttpRequest::getQuery('invite_id');
		if($invite_id!=""){
			$find_invite_id = Randomlookups::model()->find("random_num='$invite_id'");
			//echo $find_invite_id
			//exit;
			if($find_invite_id)
			{
				//$user_model->name = 
				$user_model->circle_beneficiary = $find_invite_id->user_id;
				//$invite_sender_details = Users::model()->find("id='$user_id'");
				//$user_model->circle_beneficiary = 
			}
			else{
				throw new CHttpException(400,"The url is invalid. Please contact <a href='mailto:team@helixeffort.com'>helixeffort Team</a>");
			}
		}
		$transaction = Yii::app()->db->beginTransaction();
		try
		{	
			if(isset($_POST['Users']))
			{
				$user_model->attributes=$_POST['Users'];
				$user_model->date_added = new CDbExpression('NOW()');
				$user_model->last_modified = '0000-00-00 00:00:00';
				$user_model->status = 'a';
				$password = $user_model->password;
				$user_model->password = new CDbExpression("password('".$user_model->password."')"); // Need to sanitize

				if($user_model->validate())
				{
					$user_model->save();
					$id = $user_model->id;
				}
			}

		if(isset($_POST['CreatorDetails'])&& isset($id))
		{
			$creator_model->attributes=$_POST['CreatorDetails'];
			$creator_model->user_id = $user_model->id;
			if($creator_model->validate())
			{
				$creator_model->save();
			}
			$transaction->commit();
			$this->redirect(array('auth/login','username'=>$user_model->username, 'password'=>$password));
			//$this->render('welcome',array('user_model'=>$user_model));
			//$this->redirect(array('view','id'=>$user_model->id));
		}
	}
	catch(Exception $e)
        {
        	$transaction->rollback();
        }
	$this->render('register',array('user_model'=>$user_model, 'creator_model'=>$creator_model));
	}

	public function actionWelcome()
	{
	$this->render('welcome');
	}
}

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/layout.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Helixeffort - Consume, Appreciate, Hyperproduce</title>
<link href="<?php echo $this->assetsBase ?>/css/templatemo_style.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->assetsBase ?>/css/showcase.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->assetsBase ?>/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

	<script src="http://bootsnipp.com/js/jquery.js"></script>
	<script src="http://bootsnipp.com/js/bootstrap.min.js"></script>

<? Yii::app()->clientScript->registerCoreScript('jquery');
Yii::app()->clientScript->registerCoreScript('jquery.ui');
Yii::app()->clientScript->registerCssFile(
Yii::app()->clientScript->getCoreScriptUrl().'/jui/css/base/jquery-ui.css');

 ?>
<!--<script type="text/javascript" src="js/ddsmoothmenu.js">
</script>-->

<script type="text/javascript">

/*ddsmoothmenu.init({
	mainmenuid: "templatemo_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})
*/
</script>

</head>
<body>


<div id="templatemo_wrapper">

<?
$user = 'Guest';
$logged_in = Yii::app()->user->getState('logged_in');
if($logged_in){
$profile = Yii::app()->user->getState('profile');
$user = $profile->name;
}
?>

<div class="navbar navbar-inverse nav" style="margin-bottom: 0px;">
    <div class="navbar-inner">
    <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
    <a class="brand" href="/">HE Logo </a>
    <div class="nav-collapse collapse">
    <ul class="nav" >
    <li class="divider-vertical"></li>
    <!--<li><a href="#"><i class="icon-home icon-white"></i> </a></li>-->
    </ul>
    <div class="pull-right">
    
    <ul class="nav pull-right">
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <?=$user ?> <b class="caret"></b></a>
    <ul class="dropdown-menu" style="z-index: 1000;">
    <li><a href="/user/preferences"><i class="icon-cog"></i> Preferences</a></li>
    <li><a href="/help/support"><i class="icon-envelope"></i> Contact Support</a></li>
    <li class="divider"></li>
    <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
    </ul>
    </li>
    </ul>
    </div>
    </div>
    </div>
    </div>
    </div>
  
	<!--   		<div id="templatemo_search">
            <form action="#" method="get">
              <input type="text" value="Search" name="keyword" id="keyword" title="keyword" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" length=100 />
              <input type="submit" name="Search" value="" alt="Search" id="searchbutton" title="Search" class="sub_btn"  />
            </form>
        </div>-->
<!-- end of top -->
    
    <div id="templatemo_header">
    	<div id="site_title"><a href="http://www.helixeffort.com">&nbsp;</a></div>
        <div id="templatemo_menu" class="ddsmoothmenu">
						<div align="center" style="font-size:15px;">Universal Worth</div>
						<div align="center" style="clear:both; font-size:35px; padding: 10px 10px;">1.05</div>
						<? if(!$logged_in){ ?>
						<div style="clear:both;" align="center"><a href="<?php echo $this->createUrl('users/register'); ?>" style="font-size:15px;">Register as a Creator/User</a></div>
						<div style="clear:both;" align="center"><a href="<?php echo $this->createUrl('auth/login'); ?>" style="font-size:15px;">Sign in</a></div>
						<? }else{ ?>
						<div style="clear:both;" align="center"><a href="<?php echo $this->createUrl('itemDetails/create'); ?>" style="font-size:15px;">Add New Item</a></div>
						<div style="clear:both;" align="center"><a href="<?php echo $this->createUrl('itemDetails/index'); ?>" style="font-size:15px;">List Existing Items</a></div>
						<? } ?>
	</div>
	</div>	

<?php echo $content; ?>

    
    <div id="templatemo_footer">
    	<div class="col_4">
        	<h5>Quick Links:</h5>
            <ul class="footer_list">
            	<li><a href="#">FAQs</a></li>
                <li><a href="#">Theory</a></li>
                <li><a href="">Community</a></li>
                <li><a href="blog.html">Privacy Policy</a></li>
                <li><a href="contact.html">Disclaimers</a></li>
			</ul>
        </div>
        <div class="col_4">
        	<h5>&nbsp;</h5>
            <ul class="footer_list">
                <li><a href="#">Site Map</a></li>
            	<li><a href="#">helixeffort.org</a></li>
                <li><a href="#">Contact Us</a></li>
               <!-- <li><a href="#"></a></li>
                <li><a href="#"></a></li>-->
		</ul>             
        </div>
        <div class="col_4">
        	<h5>Twitter</h5>
            <ul class="twitter_post">
	            <li>Suspendisse at scelerisque urna. Aenean tincidunt massa in tellus varius. <a href="#">http://bit.ly/13IwZO</a></li>
                <li>Proin dignissim, diam nec enim lorem tempus orci, ac ante purus in justo scelerisque. <a href="#">http://bit.ly/34sdPo</a></li>
			</ul>
        </div>
        <div class="col_4 col_l">
        	<h5>Follow Us</h5>
            <p><a href="http://www.templatemo.com" target="_parent">Lorem ipsum</a> Suspendisse at scelerisque urna. Aenean tincidunt massa in tellus varius. <a href="#">In scelerisque</a> egestas est non convallis at nisi.</p>
            <div class="footer_social_button">
                <a href="#"><img src="<?php echo $this->assetsBase ?>/images/facebook-32x32.png" title="facebook" alt="facebook" /></a>
                <a href="#"><img src="<?php echo $this->assetsBase ?>/images/flickr-32x32.png" title="flickr" alt="flickr" /></a>
                <a href="#"><img src="<?php echo $this->assetsBase ?>/images/twitter-32x32.png" title="twitter" alt="twitter" /></a>
                <a href="#"><img src="<?php echo $this->assetsBase ?>/images/youtube-32x32.png" title="youtube" alt="youtube" /></a>
                <a href="#"><img src="<?php echo $this->assetsBase ?>/images/rss-32x32.png" title="rss" alt="rss" /></a>
			</div>
		</div>
        <div class="cleaner"></div>
    </div>
    
</div> <!-- end of wrapper -->

<div id="templatemo_cr_bar_wrapper">
	<div id="templatemo_cr_bar">
    	© 2013 All rights reserved. <a href="http://www.helixeffort.com" target="_parent">Helixeffort.com</a>
    </div>
</div>
		<script type="text/javascript" src="<?php echo $this->assetsBase ?>/js/jquery-easing-min.js"></script>
		<script type="text/javascript" src="<?php echo $this->assetsBase ?>/js/jquery.ExpandyShowcase.js"></script>
		<script type="text/javascript">
			$(window).load(function() {
				$('#expandy').expandyShowcase({
					'animationDuration' : 250,
					'slideEasing'		    : 'swing',
					'compressedSize'	  : '150px',
					'expandedSize'		  : '300px',
					'firstOpen'	    : 3
				});
			});
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
$(document).ready(function(){
$('.dropdown-toggle').dropdown();
});
</script>

</body>
</html>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>