protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	 
	//$layout = 'layout';
	
	public function init() {
		//parent::init();
		$this->layout = '/layouts/layout-new';
	}
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index1');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	public function actionConcept()
	{
		$this->render('concept');
	}
	
	public function actionHowitworks()
	{
		$this->render('howitworks');
	}
	
	public function actionThehelixeffortproject()
	{
		$nav_id = CHttpRequest::getQuery('id');
		
		$this->render('thehelixeffortproject', array('nav_id'=>$nav_id));
	}
	
	public function actionFeedback()
	{
		$this->render('feedback');
	}
	
	public function actionFaq()
	{
		$this->render('faqs');
	}
}

protected/views/site/concept.php
<div class="container" style="background:white; border-radius:1px;">
        <div class="row">
  	<div class="span1 lb_col">
    	</div>
  	<div class="span9 lb_inner">
      
<div id="faq">
<h1 class="subh1">Concept</h1>
Add content here , a demo for pavan
</div>
</div>
</div>
</div>

protected/views/site/contact.php
<?php
$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

protected/views/site/helixproject-leftnav.php
<div style="margin-top:30px; margin-left:20px; margin-right: 20px;">
  <div class="well sidebar-nav">
  
<? $active[1]=$active[2]=$active[3]=$active[4]=$active[5]=$active[6]=$active[7]=""; 
	$active[$nav_id] = "active";
?>
    <ul class="nav nav-list">
      <li class="<?=$active[1]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=1';?>">The helixeffort Project</a></li>
      <li class="<?=$active[2]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=2';?>">Why Retail is Good?</a></li>
      <li class="<?=$active[3]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=3';?>">What is Immediate Media?</a></li>
      <li class="<?=$active[4]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=4';?>">How do we make it work?</a></li>
      <li class="<?=$active[5]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=5';?>">What are Hyperproducts?</a></li>
      <li class="<?=$active[6]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=6';?>">Who can make hyperproducts and why would they make one?</a></li>
      <li class="<?=$active[7]?>"><a href="<? echo $this->createUrl('site/thehelixeffortproject') . '&id=7';?>">Will it affect the way my creations function?</a></li>
    </ul>
    </div>
  </div><!--/.well -->
</div>

protected/views/site/howitworks.php
<div class="container" style="background:white; border-radius:1px;">
        <div class="row">
  	<div class="span1 lb_col">
    	</div>
  	<div class="span9 lb_inner">
      
<div id="faq">
<h1 class="subh1">How it works</h1>
Add content here
</div>
</div>
</div>
</div>

protected/views/site/hyperproducts.php
<h3>What are hyperproducts?</h3>
<p>		
<p>
“If there are a number of people who'll only use your product if it costs them $0, that's a pretty good indicator of what your product's actual value is.”
<p>
With the advent of digitizing technologies, and especially the Internet, all that was once available at only a particular place and at a particular moment is now available to us anywhere, along with and at any moment we desire. Unfortunately, or fortunately for many today, creations and information are accessible to the end user outside of its original ‘packing’ within boxes and cases; and irrespective of how the people who made it intending it to reach their chosen set of audience. And with this, experiences are multiplying and the value of appreciation for content steadily increasing while net revenues still remaining a chief concern. Until there is a continuous effort on behalf of the creators/producers to establish a relationship with their audiences, expecting real products to penetrate them is only a limited possibility. One of the major reasons that retail products are being neglected is because people want experiences, and objects don’t necessarily have to satisfy that in this digital age. This is where hyperproducts come into play, post-experience. On helixeffort, you don’t need to sell hyperproducts. The audience builds hyperproducts.
<p>
A hyperproduct is a commodity made from an end user by driving significant units of consumption and appreciation of information and content based on an “experience” factor. They have been designed in such a way to be accessible to that population where appreciation lies. It channelizes it into a distinct unit of sustainable value directly offerable to the creators and propagators. hyperproducts are not owned or released individually by helixeffort. Each hyperproduct is an established relationship between a user and a creator and is collectively owned by either of them while containing the value of the user’s appreciation for the product or service in return, stored in it forever. So basically, hyperproducts are virtual commodities containing some amount of monetary value and some amount of information. Hyperproducts are designed keeping in mind that they are always made by the user in a fractional moment of reciprocative judgment from their experience. While this judgment lasts for a short while and is bound to change hyperproducts try to snapshot that miniscule moment and begins placing it within a Universal Worth stream of hyperproducts, which is a collective snapshot of all audience experiences together.
<p>
In economic terms, hyperproducts are transactions. And each transaction is a voluntary effort to define every individual’s own value to a unit or several units of consumption or appreciation apart from being a payment for the creator’s efforts. For ultimately every creator/brand needs the ability to relate to its audience to survive and function, revive and recreate, feel inspired and motivated. And with each hyperproduct, every individual has the power to contribute just as much, and maybe even a little more.

protected/views/site/immediatemedia.php
<h3>Immediate Media – Building parallel revenues from nowhere</h3>
<p>		
Immediate Media is a terminology used by helixeffort to define an item based on the way an audience perceives it. Most products and services are created, manufactured and sold in ways in which don’t always arrive in the same sense to the public. Technology, availability, practicality and negotiability redefine the way digital information is consumed ultimately. For example, a musical release on an audio CD is not always consumed that way. It most often ends up as alternative format for practicality purposes and ease of use. Even while the audio CDs have, to a certain extent, made way for single track availability for purchase, negotiability on the part of the user plays havoc to the structure of the market economy. This is where the concept of Immediate Media can look to bring balance to the situation, that is if the creators choose to use the helixeffort service while liberating and lubricating their creations otherwise.
<p>
Immediate Media can be defined as the consumption and utilization of digital resources by an audience irrespective of how it has reached them. Digital resources can be anything which is in the form of content and information be it through containers (CDs, DVDs, tapes, hard disk drives, portable & mobile devices etc.) or via the Internet; and more importantly whether consumed as per prescribed sources/resources or otherwise.
<p>
Typically the following media generally can be termed as Immediate Media because of their non-device-centric quality of existence:
<ul>
<li>Films, television programmes and video
<li>Softwares and applications
<li>Digital video games
<li>Music and audio
<li>Print media, ebooks and images (scanned or digitized)
<li>Online information and online utility services
</ul>
<p>
The qualities of Immediate Media depend on the content along with the intellectual property they contain:
<ul>
<li>it can be used without discarding or substituting other monetization methods of retail
<li>the capacity to bring in an economic advantage which otherwise the content/information’s licensing or its business model has over it <li>through an organized sales/subscription method
<li>the more defined the intellectual property of a product/service is, the more defined the consumption of Immediate Media would be
<li>the more restricted the Immediate Media is, the more protected the intellectual property by the creator
<li>the more accessed or the reach of the Immediate Media is, the greater the potential to leverage the economic advantage
<li>concept of Immediate Media being used very sparsely amongst the prevalent business models
<li>the tendency of Immediate Media is that the audience consumes or utilizes without primarily understanding or worrying about the immediate impact it can have over a creator’s “net loss” or a threat to the creation’s IP.
</ul>
<p>
In simpler words Immediate Media is instant, not-necessarily-produced and wholly depends on post-consumption rather than the producer establishing who one’s audience has to be. helixeffort will then bring that audience to the creator and provide possibilities to enhance the relationship in as many ways possible.

protected/views/site/index.php
<?php $this->pageTitle=Yii::app()->name; ?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Congratulations! You have successfully created your Yii application.</p>

<p>You may change the content of this page by modifying the following two files:</p>
<ul>
	<li>View file: <tt><?php echo __FILE__; ?></tt></li>
	<li>Layout file: <tt><?php echo $this->getLayoutFile('main'); ?></tt></li>
</ul>

<p>For more details on how to further develop this application, please read
the <a href="http://www.yiiframework.com/doc/">documentation</a>.
Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
should you have any questions.</p>

protected/views/site/index1.php
<!--<div id="templatemo_main_wrapper" style="margin-bottom: 30px;"> 
    	<div id="templatemo_main">
		 <div class="search-container" align=center>
		    <div id="code_search">
		      <h2 style="margin:auto; padding: 10px;"><span class="mega-icon mega-icon-search-input"></span> Search more than <strong>11.8M</strong> Items</h2>

		      <form method="get" id="search_form" class="search_repos" action="/search" accept-charset="UTF-8">
			<select>
			<option value=''>Creator/Artist</option>
			<option value=''>Audio</option>
			<option value=''>Audio</option>
			<option value=''>Video</option>
			<option value=''>Book</option>
			</select><input type="text" autofocus="" autocapitalize="off" tabindex="2" value="" name="q" class="search-page-input js-search-query">
		<input type="hidden" value="" name="type" id="type_value">
		<input tabindex="3" type="submit" value="Search">

			<input type="hidden" value="simplesearch" name="ref">
		</form>      <div style="clear:both;"></div>
		    </div>
		  </div>
	</div>
		
  </div>    
-->

  <div id="templatemo_main_wrapper" style="" > 
    	<div id="templatemo_main">
		 <div class="search-container" align=center>
		    <div id="code_search">
		      <h3 style="margin:auto; padding: 10px;"><span class="mega-icon mega-icon-search-input"></span>Creator Desk</h3>
		          <form class="form-horizontal">
				 <p><input type="text" class="span5" name="eid" id="name" placeholder="Name"></p>
				<p><input type="text" class="span5" name="passwd" placeholder="Email"></p>
				<p><button type="submit" class="btn btn-small">Request Invite</button>
		    </form>
		<div style="clear:both;"></div>
		    </div>
		  </div>
	</div>
		
  </div>
    <div id="templatemo_main_wrapper" > 
    	<div id="templatemo_main" align=center>
    	
        	<div class="col_2">
            	<h3>Items Added</h3>
            	<table  width=45% style="float:left;" cell-padding= "5" cellspacing="5" align=center> 
            	<tr>
            		<td>Audio</td>
            		<td>2157</td>
            	</tr>
            	<tr>
            		<td>Video</td>
            		<td>1076</td>
            	</tr>
            	<tr>
            		<td>Books</td>
            		<td>2321</td>
            	</tr>
            	<tr>
            		<td>Softwares</td>
            		<td>3241</td>
            	</tr>
		<tr>
            		<td>Games</td>
            		<td>2095</td>
            	</tr>
	       	<tr>
            		<td>Art/Craft/Designs</td>
            		<td>2198</td>
            	</tr>
		<tr>
            		<td colspan=2 align=center><a href="#">Filter</a></td>
            	</tr>
            	</table>
            	<table  width=45% style="float:right;" cell-padding= "5" cellspacing="5" align=center> 
            	<tr>
            		<td>USA</td>
            		<td>2157</td>
            	</tr>
            	<tr>
            		<td>Germany</td>
            		<td>1076</td>
            	</tr>
            	<tr>
            		<td>Sweden</td>
            		<td>2321</td>
            	</tr>
            	<tr>
            		<td>Japan</td>
            		<td>3241</td>
            	</tr>
		<tr>
            		<td>India</td>
            		<td>20395</td>
            	</tr>
	       	<tr>
            		<td>Australia</td>
            		<td>3187</td>
            	</tr>
		<tr>
            		<td colspan=2 align=center><a href="#">Filter</a></td>
            	</tr>
            	</table>
        	<div style="clear:both;"></div>        	
            </div>
            <div class="col_2 fp_rp_pp">
            	<h3>Items Hyperproduced</h3>
            	<table  width=45% style="float:left;" cell-padding= "5" cellspacing="5"> 
            	<tr>
            		<td>Audio</td>
            		<td>2157</td>
            	</tr>
            	<tr>
            		<td>Video</td>
            		<td>1076</td>
            	</tr>
            	<tr>
            		<td>Books</td>
            		<td>2321</td>
            	</tr>
            	<tr>
            		<td>Softwares</td>
            		<td>3241</td>
            	</tr>
		<tr>
            		<td>Games</td>
            		<td>2095</td>
            	</tr>
	       	<tr>
            		<td>Art/Craft/Designs</td>
            		<td>2198</td>
            	</tr>
		<tr>
            		<td colspan=2 align=center><a href="#">Filter</a></td>
            	</tr>
            	</table>
            	<table  width=45% style="float:right;" cell-padding= "5" cellspacing="5"> 
            	<tr>
            		<td>Retail Virtual</td>
            		<td>2157</td>
            	</tr>
            	<tr>
            		<td>Virtual Commerce</td>
            		<td>1076</td>
            	</tr>
            	<tr>
            		<td>Pay per usage</td>
            		<td>2321</td>
            	</tr>
            	<tr>
            		<td>Donation</td>
            		<td>3241</td>
            	</tr>
		<tr>
            		<td>....</td>
            		<td>20395</td>
            	</tr>
	       	<tr>
            		<td>....</td>
            		<td>3187</td>
            	</tr>
		<tr>
            		<td colspan=2 align=center><a href="#">Filter</a></td>
            	</tr>
            	</table>
        	
        </div> <!-- end of main -->
<div style="clear:both;"></div>
    </div> 
</div>    
    <!-- end of main wrapper -->

  <div id="templatemo_main_wrapper" align="center"> 
    	<div id="templatemo_main">
		<h3 align=center>Top Items Hyperproduced</h3>
		<ul id="expandy" class="cf">
			<li class="first active" style="width: 500px;">
				<a href="http://www.google.co.uk">
					<h2 style="font-size: 32px;">Google</h2>
					<p>lorem ipsum dolor sit amet</p>
				</a>
			</li>
			<li class="second">
				<a href="http://www.bing.co.uk">
					<h2>Bing</h2>
					<p>lorem ipsum dolor sit amet</p>
				</a>
			</li>
			<li class="third">
				<a href="http://www.yahoo.co.uk">
					<h2>Yahoo</h2>
					<p>lorem ipsum dolor sit amet</p>
				</a>
			</li>
			<li class="fourth">
				<a href="http://www.duckduckgo.com">
					<h2>Duck Duck Go</h2>
					<p>lorem ipsum dolor sit amet</p>
				</a>
			</li>
			<li class="fifth">
				<a href="http://www.lmgtfy.com">
					<h2>Let Me Google That For you</h2>
					<p>lorem ipsum dolor sit amet</p>
				</a>
			</li>
			<li class="sixth">
				<a href="http://www.github.com">
					<h2>GitHub</h2>
					<p>lorem ipsum dolor sit amet</p>
				</a>
			</li>
		</ul>
	</div>
		
  </div>

protected/views/site/login.php
<?php
$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

<!--	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>-->

	<div class="row buttons">
		<?php echo CHtml::submitButton('Login'); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/site/make-it-work.php
<h3>How do we make it work?</h3>
<p>		
<li>Individual consumes/utilizes a digital resource (maybe a book, an e-reading software, etc.) irrespective of how they have obtained it or how the experience has reached them
<li>Generates an impression
<li>Willingness to convert the impression into a recognizable/contributive form understanding that now there is an easier resource to do that
Logs into helixeffort
<li>Creates an hyperproduct* for the particular product/service/creator/participant by reimbursing a fee equivalent to the impression gathered from the experience guided by the ‘hyperproduct assessment tool’


<li>helixeffort records the hyperproduct into a Universal Worth system signifying change, contribution and participation in terms with a social scale enabling individuals to empower creations in their own ways 

<p>
*provided the creator registers onto the helixeffort service

protected/views/site/project.php
<h3>The helixeffort Project</h3>
<p>		
“A great deal of innovation comes from extremely large and lengthy investments of time and money, and wouldn't otherwise be viable if a reasonable monetary return couldn't be guaranteed.” - TweakGuides
<p>
the helixeffort project intends to be an alternative model of economy which would be of use to the general public as well as an opportunity for content creators, content owners and artists all over the world to enable an enhanced audience interaction, recognize appreciation and to identify revenue potentials. The model will be designed to function effectively on behavioural economics through “consumption” and “appreciation” of digital media, digital information or simply any “creative work” consumable by the public, mostly digitally. With such a model present the initiative will look to bring about a meaningful and aesthetic relationship between a random consumer and a creator of digitally enabled works and also, quite importantly, propagators (with respect to reach and availability) of such content. 
<p>
<div style="margin: 0 auto; text-align: left; width:50%"><img alt="joostrap-logo-demo" src="<?php echo $this->assetsBase ?>/images/project.png" ></div>

<p>
In simple words, helixeffort is a system where a user could conveniently contribute “money” to content which exists in some or the other digital form such that the organization, group, entity or a person essentially related to its establishment or creation feels rightfully appreciated and hence motivated. This appreciation potential will be built on the fact that there has been no direct monetary returns to the beneficiary otherwise from that user for that content. Although this is not necessary, it forms the most basic aspect of this economy. The system will look to bring about unconventional techniques in the field of behavioural economics using online technologies for an improved audience interaction with the creators. This theory directly deals with the ‘free rider problem’ occurring for mass piracy, file-sharing and duplication happening over the Internet.
<p>
The model, although not completely and deliberately structured upon, does borrow basic principles of a traditional gift economy system; the concept of a Street Performer’s Protocol – i.e. a pay-what-you-want mechanism; and a moderated Escrow system (which will be introduced in the future phases of the project). This, along with a reciprocation value, will try to emulate the features of a ‘tangible product’ and will give rise to an environment (such as that within a stock-exchange) where value of every transaction and action within the system will be mathematically simulated to arrive at socially consumable values which will again look to feedback the process into the system. A gift economy is said to prevail when goods and services are exchanged like barter for no immediate returns or favours. In order to initiate the principle functioning of this economy it is necessary for the creation to be already consumed or to be allowed to be consumed in some way or the other. What the model will then intend to do is to introduce a platform for the consumers of these creations and to enable them (to put it in any words the audience chooses to) to purchase, subscribe, express gratitude or extend support to the creators by monetary means which can describe value of the content, and thus completing the circle of why the creation was actually made in the first place. That is -a creation was made, consumed, value expressed and a computative investment of time, resource and energy repaid based on the actually feedback on the value of consumption. Thus the economy described here, which will function as a business model, is to enable completion of this full circle through the helixeffort web service.

protected/views/site/retail.php
<h3>Why is Retail Good?</h3>
<p>		
helixeffort defines the quality of consumption of digital content into two aspects. Likewise there are two kinds of audience who are derived from it. Never has this quality been seen before in human civilization in such a vast scale, where one can pay for something and get it while another might not pay anything and still get the same thing, or maybe even more. A majority of creators have understood the advantages and disadvantages of both of these audiences and have begun redefining ways in which they can sustain within this. The helixeffort service primarily establishes itself in a way which attributes equal benefit to both these channels terming them as retail media and Immediate Media. Retail media can be defined as anything that can be obtained or accessed which is as defined by the creator-end (with pre-determined pricing) and thereby deriving a monetizing aspect out of its content, brand or service. Immediate Media is exactly the other way around – it is undefined methods of consumption, not controlled, not curated and not monetized from the creator-end directly. helixeffort constantly crawls around the world wide web to estimate the percentage of these audiences. Both have its benefits and both have its significant disadvantages too. One thing is certain in today’s digital world is that we cannot completely seek to bargain adapting primitive methods of sustenance like how the tangible world exists. Technology has grown, and so has the amount of content the average audience is exposed to today. There is so much being consumed that practically people would run out of money if there was a chance to monetize everything out of it. Even a percentage of it is enough to safeguard the interest of the creator. But with the wide divide of retail media benefit and Immediate Media impact the struggle to establish that percentage is becoming more of a war than a livelihood.
<p>
In this premise helixeffort offers a means for creators to adapting both and deriving from both. While the service draws entirely from the concept of building monetization channels through Immediate Media it also equally stresses on building the benefit of a retail media opportunity, for without the latter the former cannot build. For ultimately there are people around the world who would like to feel, touch and smell something which they have paid for, if it is possible. So depriving them from that will deprive the creator from bringing in that ‘little bit’ more to the audience.
<p>
Just look out for the Retail it! tab on a creator page to know which creator offers that opportunity to you. 

protected/views/site/will-it-affect-my-creations.php
<h3>Will it affect the way my creations function?</h3>
<p>		
This actually depends. It depends on the business model philosophy a particular creator or his producer is operating upon. The way Immediate Media and hyperproducts function is one where there is no restriction to the way the audience is enabled to consume it. The ability of reach to the audience could be from anywhere on the internet whether streamed, downloaded, shared, borrowed or simply experienced elsewhere. This could be either purchased, subscribed or through other means with which the creator/producer had no control of. There are various economic factors as to why the creator loses control at that juncture. One is the ease that technology and infrastructure bring in that audiences seek any way possible to make it convenient for them to experience content. 
<p>
Following are most of the ways in which creators choose to monetize their works, either separately or as a combination of many:
<h4>Direct revenue</h4>
<ul>
<li>Retail purchase
<li>Virtual retail purchase
<li>Virtual digital purchase
<li>Pay per usage
<li>Pay for support/add-ons/feature
<li>Pay-what-you-want/can
<li>Donation
</ul>
<h4>Secondary revenue</h4>
<ul>
<li>Media events
<li>Merchandising
</ul>
<h4>Indirect revenue</h4>
<ul>
<li>Digital real estate
<li>Royalty
</ul>

<h4>Investments, capitals and funding </h4>

helixeffort tries to bring in a little of most of the above together thereby bringing stability to the way the audience perceives what they end up consuming. Along with this the service strongly suggests to retain the retail methods of propagation (retail-is-good philosophy) since retailing creations are the purest form of commerce that equates resources in a justifiable manner. While Immediate Media helps in navigating through problems of availability and accessibility in regions where physical products are hard to come by hyperproducts could impact the way physical products would function in places where retail plays a huge role. Negotiating through individual chosen business models is through the effort of the creators and the producers. The idea of copyright might have to be altered with the helixeffort business model (license – Phase II) which will state the fair usage of Immediate Media occurrences. Also the other players responsible for the retail production of products will be impacted to a certain extent and a thorough understanding of the implications have to be considered before choosing the helixeffort service (along with the T&C).